name: Semgrep CI Scan
on:
  push:
    branches:
      - main
      - test-branch
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    name: Run Semgrep Scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config auto